function getDestacades() {
    return '["imatges/birds.jpg","imatges/cars.jpg","imatges/dory.jpg","imatges/luxo.jpg","imatges/monstruos.jpg","imatges/soul.jpg","imatges/up.jpg"]';
}

function getFilmsACA() {
    return '[{"filmId":1,"title":"ACADEMY DINOSAUR","description":"A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies","releaseYear":1136070000000,"rentalRate":0.99,"length":86,"rating":"PG","specialFeatures":"Deleted Scenes,Behind the Scenes"},{"filmId":114,"title":"CAMELOT VACATION","description":"A Touching Character Study of a Woman And a Waitress who must Battle a Pastry Chef in A MySQL Convention","releaseYear":1136070000000,"rentalRate":0.99,"length":61,"rating":"NC-17","specialFeatures":"Trailers,Commentaries,Deleted Scenes,Behind the Scenes"},{"filmId":930,"title":"VACATION BOONDOCK","description":"A Fanciful Character Study of a Secret Agent And a Mad Scientist who must Reach a Teacher in Australia","releaseYear":1136070000000,"rentalRate":2.99,"length":145,"rating":"R","specialFeatures":"Commentaries"},{"filmId":940,"title":"VICTORY ACADEMY","description":"A Insightful Epistle of a Mad Scientist And a Explorer who must Challenge a Cat in The Sahara Desert","releaseYear":1136070000000,"rentalRate":0.99,"length":64,"rating":"PG-13","specialFeatures":"Trailers,Behind the Scenes"}]';
}

function getActors1(){return '[{"actorId":1,"firstName":"PENELOPE","lastName":"GUINESS"},{"actorId":10,"firstName":"CHRISTIAN","lastName":"GABLE"},{"actorId":20,"firstName":"LUCILLE","lastName":"TRACY"},{"actorId":30,"firstName":"SANDRA","lastName":"PECK"},{"actorId":40,"firstName":"JOHNNY","lastName":"CAGE"},{"actorId":53,"firstName":"MENA","lastName":"TEMPLE"},{"actorId":108,"firstName":"WARREN","lastName":"NOLTE"},{"actorId":162,"firstName":"OPRAH","lastName":"KILMER"},{"actorId":188,"firstName":"ROCK","lastName":"DUKAKIS"},{"actorId":198,"firstName":"MARY","lastName":"KEITEL"}]';
}